const homePage = require('../pages/home.page')
const constants = require('../constants')
const elementUtil = require('../util/elementUtil')

describe('Home Page features test: ', function(){
    const start = Date.now()
    it('Check browser details', function() {
    browser.url('https://www.whatismybrowser.com')
    const elem = $('.string-major')
    const result = elem.getText()
    })
    it('Should have the correct URL and title', function(){
        browser.url('/intl/v/car-safety/a-million-more')
        browser.maximizeWindow()
        const URLtitle = browser.getUrlAndTitle()
        assert.strictEqual(URLtitle.url, constants.HOME_PAGE_URL)    
        assert.strictEqual(URLtitle.title, constants.HOME_PAGE_TITLE)
    })
    it('Video button exists', function() {
        const vid = homePage.isVideoButtonExists()
        assert.equal(true, vid, 'Video button missing')
    })
    it('Disclaimer Section exists', function() {
        const dis = homePage.isDisclaimerExists()
        assert.equal(true, dis, 'Disclaimer missing')
    })
    it('Play Video, go to Cookies Page and check Title', function() {
        browser.url('/intl/v/car-safety/a-million-more')
        const paragraph = $("//div[2]/div/button[contains(text(),'Accept')]")
        paragraph.click()
		browser.pause(5000)
        const watchVid = $("//div/button[contains(text(),'watch the story')]")
        watchVid.click()
		browser.pause(3000)
        const cookies = $("//span[1]/a[1][contains(text(),'Cookies')]")
        cookies.click()
		browser.pause(5000)
        const cookieTitle = browser.getUrlAndTitle()
        assert.strictEqual(cookieTitle.url, constants.COOKIE_PAGE_URL)
        assert.strictEqual(cookieTitle.title, constants.COOKIE_PAGE_TITLE)
        console.log('Time taken :')
        console.log((Date.now() - start)/1000+' seconds')
    })
})